### ISSUE TITLE
MRD Data opened in Python appears corrupted

### ISSUE THREAD

**Issue by gabuzi** [cncastillo/KomaMRI.jl#214] opened 2023-11-15 15:31 UTC
Hi all!

I've just taken KomaMRI.jl for a quick test-drive and I noticed that I can't open the resulting ismrmrd files with the ismrmrd-python package. Reason seems to be a second nested level of the `<UserParameters>` element (see below). I also spotted a potential problem with the gpu user param value (annotated in the snippet below).

I used v0.7.6 with julia 1.9.1

```xml
<?xml version="1.0" encoding="utf-8"?>
<ismrmrdHeader xsi:schemaLocation="http://www.ismrm.org/ISMRMRD ismrmrd.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.ismrm.org/ISMRMRD" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
 ...
<userParameters>
    <userParameters> <!-- this one here! -->
      <userParameterLong>
        <name>Nblocks</name>
        <value>2195</value>
      </userParameterLong>
      <userParameterLong>
        <name>gpu</name>
        <value>false</value> <!-- this may be another issue as value 'false' is not a valid xs:long value -->
      </userParameterLong>
      <userParameterLong>
        <name>gpu_device</name>
        <value>0</value>
      </userParameterLong>
      <userParameterString>
        <name>precision</name>
        <value>f32</value>
      </userParameterString>
      <userParameterString>
        <name>return_type</name>
        <value>raw</value>
      </userParameterString>
      <userParameterDouble>
        <name>Δt_rf</name>
        <value>5.0e-5</value>
      </userParameterDouble>
      <userParameterLong>
        <name>Nthreads</name>
        <value>1</value>
      </userParameterLong>
      <userParameterString>
        <name>sim_method</name>
        <value>Bloch()</value>
      </userParameterString>
      <userParameterDouble>
        <name>sim_time_sec</name>
        <value>15.131958583</value>
      </userParameterDouble>
      <userParameterDouble>
        <name>Δt</name>
        <value>0.001</value>
      </userParameterDouble>
    </userParameters> <!-- this one here! -->
  </userParameters>
</ismrmrdHeader>
```

--------------------------------------
EDIT 1-Dec-2023 (@cncastillo):

Hi I think this issue can be separated in two:

- [x] #236
- [ ] Incorrect byte size of `AcquisitionHeader` in exported MRD

**Comment by cncastillo** [comment] 2023-11-15 17:12
Hi @gabuzi, thanks for noticing this. I was aware that there could be a problem with the .mrd and Python's MRD reader. As when I tried it it also did not work. This helps us fix it.

If there is problem with the `userParameters` XML header having not-numeric stuff we can easily change it.

Could you send us the code to open an .mrd in Python? I assume you opened the UI, pressed simulate, and tried opening the resulting .mrd located in the temp folder. Just to try to reproduce this.

**Comment by cncastillo** [comment] 2023-11-15 19:40
Hi can any of you attach a valid MRD to compare?

**Comment by tknopp** [comment] 2023-12-02 10:01
Oh, this is really bad. I have not seen https://ismrmrd.readthedocs.io/en/latest/mrd_raw_data.html#acquisitionheader and assumed that the offsets correspond to the in-memory layout of the C struct (which in Julia is the immutable header type). And when I worked on this, I actually have seen the padded data in some public MRM files.

So am I reading https://ismrmrd.readthedocs.io/en/latest/mrd_raw_data.html#acquisitionheader  correctly, that the layout is always tight, i.e. that do padding is involved? In that case `myfieldoffset` seems to be the correct implementation and we then would not need to hardcode the actual table.

One issue though is that I don't understand how we can present the "unpadded" struct in Julia. Does somebody know how this is handled in the C bindings? The C struct will also have such padding.

**Comment by tknopp** [comment] 2023-12-02 10:16
Looking at https://github.com/ismrmrd/ismrmrd/blob/master/libsrc/serialization.cpp#L11 it seems that the C struct is also serialized directly. I don't get that. Does it mean that the C struct is not padded?

To solve this issue it would be great to ping somebody, how has more experience with the C/C++ implementation and can clarify these questions.

**Comment by tknopp** [comment] 2023-12-03 07:36
C structs are padded by default unless you tell the compiler not to do so. But have found the line where this is actually done:
https://github.com/ismrmrd/ismrmrd/blob/d364e03d3faa3ca516da7807713b5acc72218a37/include/ismrmrd/ismrmrd.h#L82C1-L82C13
So with that all is clear.

I already did a little bit of research how we can solve this. Unfortunately we can't disable structural padding. But I think we will simply convert the struct to an `UInt8` Array and that should do the trick.

**Comment by tknopp** [comment] 2023-12-03 09:21
And for reference: In our unit test we use the ISMRMRD data:
https://sourceforge.net/projects/ismrmrd/files/data/

And that seems to be padded. Would be great if someone could have a look and inspect that data. I can't load it with the python ismrmrd library but don't know where the issue is.

So what I would definitely also need to fix the issue is correct data. Ideally again, some cartesian and spiral data. What is also important is that the data is small, so that we can use it in the unit tests.

**Comment by cncastillo** [comment] 2023-12-04 11:14
Hi @tknopp, Thanks for looking into this. 

I have tested the fix with cartesian and spiral data generated with Koma, and I think it does in fact solve the problem, as I do not see the data being corrupted in Python anymore. I will do further testing, but I believe I will close this issue soon :).

**Comment by tknopp** [comment] 2023-12-04 11:25
Great, thanks so much for reporting. I did, by the way, already do the releases (including the move of the Limit... types) so you can already rely on that in Koma.

**Closed** 2023-12-20 20:22 UTC
Labels: 1) high priority
